server:
  port: 8080
  servlet:
    context-path: /online_shop/
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/online_shop
    username: root
    password:
  jpa:

    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    enabled: true
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
